# Generated by Django 3.1 on 2021-04-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_album_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='description',
        ),
    ]
