# Generated by Django 3.1 on 2021-04-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_album_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='user',
        ),
        migrations.AddField(
            model_name='album',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
